version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-clean-arch-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - PORT=${PORT}
      - ENV=${ENV}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_SSL_MODE=${DB_SSL_MODE}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION_HOURS=${JWT_EXPIRATION_HOURS}
    volumes:
      - .:/app  # Mount local code into container
    restart: unless-stopped
    networks:
      - go-clean-arch-network

  postgres:
    image: postgres:17-alpine
    container_name: go-clean-arch-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infrastructure/database/migrations:/docker-entrypoint-initdb.d
    restart: unless-stopped
    networks:
      - go-clean-arch-network

volumes:
  postgres_data:
networks:
  go-clean-arch-network:
    driver: bridge